name: build-deploy

on:
  push:
    branches:
      master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the site in the jekyll/builder container
      uses: actions/checkout@master
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.TC_HOST }}
        username: ${{ secrets.TC_USER }}
        password: ${{ secrets.TC_PASSWORD }}
        port: ${{ secrets.TC_PORT }}
        source: "${{ github.workspace }}/_site/*"
        target: "$HOME/blog/"

